Resolve issue with reusing connections on Froyo (2.2) and older
In certain circumstances when attempting to reuse a connection on
Android 2.2 and older, you may receive the following exception:

IllegalArgumentException: No matching constant for [-1]

For those affected versions, the HTTP Keep-Alive header is set to false
via the following system property:

System.setProperty("http.keepAlive", "false");

Issue: ANDROID-81